/*
 * Build a 365-day deterministic daily puzzle rotation.
 * Run from this directory: node tools/build_daily_puzzle_data.js
 */
const fs = require('fs');
const path = require('path');
const puzzle = require('../src/core/puzzle_generator.js');

const CYCLE_DAYS = 365;
const RULE_OFFSET = 5;
const MULTIPLY = puzzle.OPERATORS[2];
const DIVIDE = puzzle.OPERATORS[3];
const RULES = [
  { requiredOperator: '', forbiddenOperator: DIVIDE, requiresLarge: false },
  { requiredOperator: '', forbiddenOperator: '', requiresLarge: false },
  { requiredOperator: '', forbiddenOperator: '', requiresLarge: true },
  { requiredOperator: '-', forbiddenOperator: '', requiresLarge: false },
  { requiredOperator: MULTIPLY, forbiddenOperator: '', requiresLarge: false },
  { requiredOperator: '', forbiddenOperator: MULTIPLY, requiresLarge: false },
  { requiredOperator: '', forbiddenOperator: '+', requiresLarge: false },
  { requiredOperator: '', forbiddenOperator: '', requiresLarge: false },
];
const STAGE_PROFILES = [
  { minimumScore: 4, maximumSolutions: 40 },
  { minimumScore: 6, maximumSolutions: 24 },
  { minimumScore: 8, maximumSolutions: 16 },
  { minimumScore: 9, maximumSolutions: 12 },
  // 受禁用运算符规则影响，极限题优先保证高难度；解法数量放宽到 12，
  // 避免某些规则日因合法题池过窄而无法完成全年轮换。
  { minimumScore: 10, maximumSolutions: 12 },
];

function key(numbers) {
  return numbers.join(',');
}

function hash(text, seed) {
  let value = (Number(seed) >>> 0) ^ 2166136261;
  for (const char of text) {
    value ^= char.charCodeAt(0);
    value = Math.imul(value, 16777619);
  }
  return value >>> 0;
}

function makePools() {
  return RULES.map((rule, ruleIndex) => {
    const pool = [];
    for (let first = 1; first <= 13; first += 1) {
      for (let second = first; second <= 13; second += 1) {
        for (let third = second; third <= 13; third += 1) {
          for (let fourth = third; fourth <= 13; fourth += 1) {
            const numbers = [first, second, third, fourth];
            if (rule.requiresLarge && !numbers.some((value) => value >= 10)) continue;
            const record = puzzle.makeVerifiedRecord(
              numbers,
              3000 + ruleIndex,
              0,
              1,
              40,
              rule.requiredOperator,
              rule.forbiddenOperator,
              false,
            );
            if (record && record.numbers) pool.push(record);
          }
        }
      }
    }
    return pool;
  });
}

function build() {
  const pools = makePools();
  const days = Array.from({ length: CYCLE_DAYS }, () => ({ rule_index: 0, puzzles: [] }));
  // 优先避免同一规则全年重复；题池耗尽后允许低频复用。
  // 同一天始终使用 usedToday，保证五道题不会重复。
  const usedByRule = Array.from({ length: RULES.length }, () => new Set());
  const daysByRule = Array.from({ length: RULES.length }, () => []);
  for (let day = 0; day < CYCLE_DAYS; day += 1) daysByRule[(day + RULE_OFFSET) % RULES.length].push(day);

  // Restrictive rules receive their valid pool first so other rules cannot consume it.
  const ruleOrder = [5, 6, 0, 3, 4, 2, 1, 7];
  for (const ruleIndex of ruleOrder) {
    const used = usedByRule[ruleIndex];
    for (const day of daysByRule[ruleIndex]) {
      const usedToday = new Set();
      const ordered = pools[ruleIndex].slice().sort((left, right) => {
        const seed = 20260000 + day * 7919 + ruleIndex;
        return hash(key(left.numbers), seed) - hash(key(right.numbers), seed);
      });
      for (let stage = 0; stage < STAGE_PROFILES.length; stage += 1) {
        const profile = STAGE_PROFILES[stage];
        const minimumScore = profile.minimumScore;
        const maximumSolutions = profile.maximumSolutions;
        let selected = ordered.find((record) => (
          !used.has(key(record.numbers))
          && !usedToday.has(key(record.numbers))
          && record.difficultyScore >= minimumScore
          && record.solutionCount <= maximumSolutions
        ));
        if (!selected) selected = ordered.find((record) => (
          !used.has(key(record.numbers))
          && !usedToday.has(key(record.numbers))
          && record.difficultyScore >= minimumScore - 2
        ));
        // 规则题池在极少数日期可能没有满足严格解法数量的候选，
        // 先从同规则全年未使用题目中兜底，再允许极端情况下同日外复用。
        if (!selected) selected = ordered.find((record) => !used.has(key(record.numbers)) && !usedToday.has(key(record.numbers)));
        if (!selected) selected = ordered.find((record) => !usedToday.has(key(record.numbers)));
        if (!selected) throw new Error(`daily puzzle generation failed: day=${day}, rule=${ruleIndex}, stage=${stage}`);
        used.add(key(selected.numbers));
        usedToday.add(key(selected.numbers));
        days[day].rule_index = ruleIndex;
        days[day].puzzles.push(selected.numbers);
      }
    }
  }

  const uniqueQuestions = usedByRule.reduce((total, set) => total + set.size, 0);
  const output = `// Generated by tools/build_daily_puzzle_data.js\nmodule.exports = ${JSON.stringify({ version: 2, cycle_days: CYCLE_DAYS, rule_offset: RULE_OFFSET, days })};\n`;
  fs.writeFileSync(path.join(__dirname, '..', 'src', 'core', 'daily_puzzle_data.js'), output, 'utf8');
  console.log(JSON.stringify({ days: days.length, questions: uniqueQuestions, pools: pools.map((pool) => pool.length), output: 'src/core/daily_puzzle_data.js' }));
}

build();
