/*
 * Build a 365-day deterministic daily puzzle rotation.
 * Run from this directory: node tools/build_daily_puzzle_data.js
 */
const fs = require('fs');
const path = require('path');
const puzzle = require('../src/core/puzzle_generator.js');

const CYCLE_DAYS = 365;
const RULE_OFFSET = 5;
const MULTIPLY = puzzle.OPERATORS[2];
const DIVIDE = puzzle.OPERATORS[3];
const RULES = [
  { requiredOperator: '', forbiddenOperator: DIVIDE, requiresLarge: false },
  { requiredOperator: '', forbiddenOperator: '', requiresLarge: false },
  { requiredOperator: '', forbiddenOperator: '', requiresLarge: true },
  { requiredOperator: '-', forbiddenOperator: '', requiresLarge: false },
  { requiredOperator: MULTIPLY, forbiddenOperator: '', requiresLarge: false },
  { requiredOperator: '', forbiddenOperator: MULTIPLY, requiresLarge: false },
  { requiredOperator: '', forbiddenOperator: '+', requiresLarge: false },
  { requiredOperator: '', forbiddenOperator: '', requiresLarge: false },
];

function key(numbers) {
  return numbers.join(',');
}

function hash(text, seed) {
  let value = (Number(seed) >>> 0) ^ 2166136261;
  for (const char of text) {
    value ^= char.charCodeAt(0);
    value = Math.imul(value, 16777619);
  }
  return value >>> 0;
}

function makePools() {
  return RULES.map((rule, ruleIndex) => {
    const pool = [];
    for (let first = 1; first <= 13; first += 1) {
      for (let second = first; second <= 13; second += 1) {
        for (let third = second; third <= 13; third += 1) {
          for (let fourth = third; fourth <= 13; fourth += 1) {
            const numbers = [first, second, third, fourth];
            if (rule.requiresLarge && !numbers.some((value) => value >= 10)) continue;
            const record = puzzle.makeVerifiedRecord(
              numbers,
              3000 + ruleIndex,
              0,
              1,
              40,
              rule.requiredOperator,
              rule.forbiddenOperator,
              false,
            );
            if (record && record.numbers) pool.push(record);
          }
        }
      }
    }
    return pool;
  });
}

function build() {
  const pools = makePools();
  const days = Array.from({ length: CYCLE_DAYS }, () => ({ rule_index: 0, puzzles: [] }));
  const used = new Set();
  const daysByRule = Array.from({ length: RULES.length }, () => []);
  for (let day = 0; day < CYCLE_DAYS; day += 1) daysByRule[(day + RULE_OFFSET) % RULES.length].push(day);

  // Restrictive rules receive their valid pool first so other rules cannot consume it.
  const ruleOrder = [5, 6, 0, 3, 4, 2, 1, 7];
  for (const ruleIndex of ruleOrder) {
    for (const day of daysByRule[ruleIndex]) {
      const ordered = pools[ruleIndex].slice().sort((left, right) => {
        const seed = 20260000 + day * 7919 + ruleIndex;
        return hash(key(left.numbers), seed) - hash(key(right.numbers), seed);
      });
      for (let stage = 0; stage < 3; stage += 1) {
        const minimumScore = stage === 0 ? 4 : stage === 1 ? 6 : 8;
        const maximumSolutions = stage === 0 ? 40 : stage === 1 ? 24 : 12;
        let selected = ordered.find((record) => (
          !used.has(key(record.numbers))
          && record.difficultyScore >= minimumScore
          && record.solutionCount <= maximumSolutions
        ));
        if (!selected) selected = ordered.find((record) => (
          !used.has(key(record.numbers)) && record.difficultyScore >= minimumScore - 2
        ));
        if (!selected) throw new Error(`daily puzzle generation failed: day=${day}, rule=${ruleIndex}, stage=${stage}`);
        used.add(key(selected.numbers));
        days[day].rule_index = ruleIndex;
        days[day].puzzles.push(selected.numbers);
      }
    }
  }

  const output = `// Generated by tools/build_daily_puzzle_data.js\nmodule.exports = ${JSON.stringify({ version: 1, cycle_days: CYCLE_DAYS, rule_offset: RULE_OFFSET, days })};\n`;
  fs.writeFileSync(path.join(__dirname, '..', 'src', 'core', 'daily_puzzle_data.js'), output, 'utf8');
  console.log(JSON.stringify({ days: days.length, questions: used.size, pools: pools.map((pool) => pool.length), output: 'src/core/daily_puzzle_data.js' }));
}

build();
