extends SceneTree

const PuzzleGeneratorScript = preload("res://core/puzzle_generator.gd")
const FriendMatchServiceScript = preload("res://core/friend_match_service.gd")
const ShareServiceScript = preload("res://services/share_service.gd")
const RewardServiceScript = preload("res://services/reward_service.gd")


func _init() -> void:
	var generator := PuzzleGeneratorScript.new()
	var room := FriendMatchServiceScript.create_room(2026081301)
	assert(str(room["room_code"]).length() == 6, "房间号应为 6 位")
	assert(int(room["rules"]["question_count"]) == 8, "好友对战应为 8 题")
	var joined := FriendMatchServiceScript.join_room(room)
	assert(joined["players"].size() == 2, "好友加入后应有两名玩家")
	assert(str(joined["status"]) == "ready", "好友加入后房间应准备完成")
	var puzzles_a := FriendMatchServiceScript.generate_puzzles(generator, int(room["room_seed"]))
	var puzzles_b := FriendMatchServiceScript.generate_puzzles(generator, int(room["room_seed"]))
	assert(puzzles_a.size() == 8, "好友房间题目数量错误")
	assert(puzzles_a[0]["numbers"] == puzzles_b[0]["numbers"], "同一房间种子必须生成相同题目")
	assert(puzzles_a[7]["numbers"] == puzzles_b[7]["numbers"], "同一房间后续题目也必须一致")
	var plan := FriendMatchServiceScript.build_opponent_plan(int(room["room_seed"]), 8)
	var snapshot := FriendMatchServiceScript.opponent_snapshot(plan, 30.0, 8)
	assert(int(snapshot["solved"]) > 0, "好友进度应随时间推进")
	var win := FriendMatchServiceScript.calculate_result(5, 800, 0, 40.0, {"solved": 4, "score": 700, "elapsed": 42.0})
	assert(str(win["outcome"]) == "win", "答对题数更多应获胜")
	var lose := FriendMatchServiceScript.calculate_result(3, 800, 1, 55.0, {"solved": 4, "score": 700, "elapsed": 42.0})
	assert(str(lose["outcome"]) == "lose", "答对题数更少应失败")
	var payload := ShareServiceScript.create_friend_room_payload(room)
	assert(str(payload["query"]).contains(str(room["room_code"])), "分享参数应包含房间号")
	assert(str(payload["query"]).contains(str(room["room_seed"])), "分享参数应包含房间种子")
	var progress := {"coins": 0}
	var reward := RewardServiceScript.claim_friend_match_reward(progress, win, "2026-08-13")
	assert(int(reward["coins"]) == 20, "好友胜利奖励错误")
	RewardServiceScript.claim_friend_match_reward(progress, lose, "2026-08-13")
	RewardServiceScript.claim_friend_match_reward(progress, lose, "2026-08-13")
	var capped := RewardServiceScript.claim_friend_match_reward(progress, win, "2026-08-13")
	assert(int(capped["coins"]) == 0, "每日好友对战奖励应有次数上限")
	print("Friend match verification passed: room, same seed, opponent progress, result, share payload and reward cap")
	quit()
