// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_accounts.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAdminAccount = `-- name: CreateAdminAccount :execresult
INSERT INTO admin_accounts (
    username,
    password_hash,
    role,
    status,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAdminAccountParams struct {
	Username     string
	PasswordHash string
	Role         string
	Status       uint8
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateAdminAccount(ctx context.Context, arg CreateAdminAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAdminAccount,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const getAdminAccountByID = `-- name: GetAdminAccountByID :one
SELECT id, username, password_hash, role, status, last_login_at, created_at, updated_at
FROM admin_accounts
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAdminAccountByID(ctx context.Context, id uint64) (AdminAccount, error) {
	row := q.db.QueryRowContext(ctx, getAdminAccountByID, id)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminAccountByUsername = `-- name: GetAdminAccountByUsername :one
SELECT id, username, password_hash, role, status, last_login_at, created_at, updated_at
FROM admin_accounts
WHERE username = ?
LIMIT 1
`

func (q *Queries) GetAdminAccountByUsername(ctx context.Context, username string) (AdminAccount, error) {
	row := q.db.QueryRowContext(ctx, getAdminAccountByUsername, username)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchAdminLastLogin = `-- name: TouchAdminLastLogin :exec
UPDATE admin_accounts
SET last_login_at = ?, updated_at = ?
WHERE id = ?
`

type TouchAdminLastLoginParams struct {
	LastLoginAt sql.NullTime
	UpdatedAt   time.Time
	ID          uint64
}

func (q *Queries) TouchAdminLastLogin(ctx context.Context, arg TouchAdminLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, touchAdminLastLogin, arg.LastLoginAt, arg.UpdatedAt, arg.ID)
	return err
}
