// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*)
FROM users AS u
WHERE (CAST(? AS CHAR) = ''
       OR CAST(u.id AS CHAR) LIKE CONCAT('%', CAST(? AS CHAR), '%')
       OR u.username LIKE CONCAT('%', CAST(? AS CHAR), '%')
       OR (CASE WHEN u.nickname_moderation_status = 'approved' THEN u.nickname ELSE '算术玩家' END) LIKE CONCAT('%', CAST(? AS CHAR), '%'))
  AND (CAST(? AS CHAR) = 'all'
       OR (CAST(? AS CHAR) = 'active' AND u.status <> 0)
       OR (CAST(? AS CHAR) = 'disabled' AND u.status = 0))
  AND (CAST(? AS CHAR) = 'all'
       OR (CAST(? AS CHAR) = 'wechat' AND EXISTS (SELECT 1 FROM user_identities AS identity_record WHERE identity_record.user_id = u.id AND identity_record.provider = 'wechat'))
       OR (CAST(? AS CHAR) = 'taptap'
           AND NOT EXISTS (SELECT 1 FROM user_identities AS identity_record WHERE identity_record.user_id = u.id AND identity_record.provider = 'wechat')
           AND EXISTS (SELECT 1 FROM user_identities AS identity_record WHERE identity_record.user_id = u.id AND identity_record.provider = 'taptap'))
       OR (CAST(? AS CHAR) = 'password'
           AND NOT EXISTS (SELECT 1 FROM user_identities AS identity_record WHERE identity_record.user_id = u.id AND identity_record.provider IN ('wechat', 'taptap'))))
`

type CountAdminUsersParams struct {
	Query    interface{}
	Status   interface{}
	Platform interface{}
}

func (q *Queries) CountAdminUsers(ctx context.Context, arg CountAdminUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers,
		arg.Query,
		arg.Query,
		arg.Query,
		arg.Query,
		arg.Status,
		arg.Status,
		arg.Status,
		arg.Platform,
		arg.Platform,
		arg.Platform,
		arg.Platform,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT u.id,
       u.username,
       u.nickname,
       u.avatar,
       u.status,
       u.nickname_moderation_status,
       u.avatar_moderation_status,
       u.moderation_updated_at,
       u.created_at,
       u.updated_at,
       CASE
           WHEN EXISTS (SELECT 1 FROM user_identities AS identity_record WHERE identity_record.user_id = u.id AND identity_record.provider = 'wechat') THEN 'wechat'
           WHEN EXISTS (SELECT 1 FROM user_identities AS identity_record WHERE identity_record.user_id = u.id AND identity_record.provider = 'taptap') THEN 'taptap'
           ELSE 'password'
       END AS platform
FROM users AS u
WHERE u.id = ?
LIMIT 1
`

type GetAdminUserRow struct {
	ID                       uint64
	Username                 string
	Nickname                 string
	Avatar                   string
	Status                   uint8
	NicknameModerationStatus string
	AvatarModerationStatus   string
	ModerationUpdatedAt      sql.NullTime
	CreatedAt                time.Time
	UpdatedAt                time.Time
	Platform                 string
}

func (q *Queries) GetAdminUser(ctx context.Context, id uint64) (GetAdminUserRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminUser, id)
	var i GetAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Avatar,
		&i.Status,
		&i.NicknameModerationStatus,
		&i.AvatarModerationStatus,
		&i.ModerationUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Platform,
	)
	return i, err
}

const getAdminUserStats = `-- name: GetAdminUserStats :one
SELECT COUNT(*) AS total,
       COUNT(CASE WHEN DATE(created_at) = UTC_DATE() THEN 1 END) AS new_today,
       COUNT(CASE WHEN status <> 0 THEN 1 END) AS active,
       COUNT(CASE WHEN status = 0 THEN 1 END) AS disabled
FROM users
`

type GetAdminUserStatsRow struct {
	Total    int64
	NewToday int64
	Active   int64
	Disabled int64
}

func (q *Queries) GetAdminUserStats(ctx context.Context) (GetAdminUserStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserStats)
	var i GetAdminUserStatsRow
	err := row.Scan(
		&i.Total,
		&i.NewToday,
		&i.Active,
		&i.Disabled,
	)
	return i, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT u.id,
       u.username,
       u.nickname,
       u.avatar,
       u.status,
       u.nickname_moderation_status,
       u.avatar_moderation_status,
       u.moderation_updated_at,
       u.created_at,
       u.updated_at,
       CASE
           WHEN EXISTS (SELECT 1 FROM user_identities AS identity_record WHERE identity_record.user_id = u.id AND identity_record.provider = 'wechat') THEN 'wechat'
           WHEN EXISTS (SELECT 1 FROM user_identities AS identity_record WHERE identity_record.user_id = u.id AND identity_record.provider = 'taptap') THEN 'taptap'
           ELSE 'password'
       END AS platform
FROM users AS u
WHERE (CAST(? AS CHAR) = ''
       OR CAST(u.id AS CHAR) LIKE CONCAT('%', CAST(? AS CHAR), '%')
       OR u.username LIKE CONCAT('%', CAST(? AS CHAR), '%')
       OR (CASE WHEN u.nickname_moderation_status = 'approved' THEN u.nickname ELSE '算术玩家' END) LIKE CONCAT('%', CAST(? AS CHAR), '%'))
  AND (CAST(? AS CHAR) = 'all'
       OR (CAST(? AS CHAR) = 'active' AND u.status <> 0)
       OR (CAST(? AS CHAR) = 'disabled' AND u.status = 0))
  AND (CAST(? AS CHAR) = 'all'
       OR (CAST(? AS CHAR) = 'wechat' AND EXISTS (SELECT 1 FROM user_identities AS identity_record WHERE identity_record.user_id = u.id AND identity_record.provider = 'wechat'))
       OR (CAST(? AS CHAR) = 'taptap'
           AND NOT EXISTS (SELECT 1 FROM user_identities AS identity_record WHERE identity_record.user_id = u.id AND identity_record.provider = 'wechat')
           AND EXISTS (SELECT 1 FROM user_identities AS identity_record WHERE identity_record.user_id = u.id AND identity_record.provider = 'taptap'))
       OR (CAST(? AS CHAR) = 'password'
           AND NOT EXISTS (SELECT 1 FROM user_identities AS identity_record WHERE identity_record.user_id = u.id AND identity_record.provider IN ('wechat', 'taptap'))))
ORDER BY u.created_at DESC, u.id DESC
LIMIT ? OFFSET ?
`

type ListAdminUsersParams struct {
	Query    interface{}
	Status   interface{}
	Platform interface{}
	Limit    int32
	Offset   int32
}

type ListAdminUsersRow struct {
	ID                       uint64
	Username                 string
	Nickname                 string
	Avatar                   string
	Status                   uint8
	NicknameModerationStatus string
	AvatarModerationStatus   string
	ModerationUpdatedAt      sql.NullTime
	CreatedAt                time.Time
	UpdatedAt                time.Time
	Platform                 string
}

func (q *Queries) ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]ListAdminUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUsers,
		arg.Query,
		arg.Query,
		arg.Query,
		arg.Query,
		arg.Status,
		arg.Status,
		arg.Status,
		arg.Platform,
		arg.Platform,
		arg.Platform,
		arg.Platform,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Nickname,
			&i.Avatar,
			&i.Status,
			&i.NicknameModerationStatus,
			&i.AvatarModerationStatus,
			&i.ModerationUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminUserStatus = `-- name: UpdateAdminUserStatus :execrows
UPDATE users
SET status = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateAdminUserStatusParams struct {
	Status    uint8
	UpdatedAt time.Time
	ID        uint64
}

func (q *Queries) UpdateAdminUserStatus(ctx context.Context, arg UpdateAdminUserStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAdminUserStatus, arg.Status, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
