// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard_submissions.sql

package db

import (
	"context"
	"time"
)

const createLeaderboardSubmission = `-- name: CreateLeaderboardSubmission :exec
INSERT INTO player_leaderboard_submissions (
    user_id,
    mode,
    idempotency_key,
    score,
    questions,
    elapsed_ms,
    room_id,
    outcome,
    metadata_json,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateLeaderboardSubmissionParams struct {
	UserID         uint64
	Mode           string
	IdempotencyKey string
	Score          uint32
	Questions      uint32
	ElapsedMs      uint32
	RoomID         string
	Outcome        string
	MetadataJson   string
	CreatedAt      time.Time
}

func (q *Queries) CreateLeaderboardSubmission(ctx context.Context, arg CreateLeaderboardSubmissionParams) error {
	_, err := q.db.ExecContext(ctx, createLeaderboardSubmission,
		arg.UserID,
		arg.Mode,
		arg.IdempotencyKey,
		arg.Score,
		arg.Questions,
		arg.ElapsedMs,
		arg.RoomID,
		arg.Outcome,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	return err
}

const getLeaderboardSubmissionByKey = `-- name: GetLeaderboardSubmissionByKey :one
SELECT id, user_id, mode, idempotency_key, score, questions, elapsed_ms, room_id, outcome, metadata_json, created_at
FROM player_leaderboard_submissions
WHERE user_id = ? AND mode = ? AND idempotency_key = ?
LIMIT 1
`

type GetLeaderboardSubmissionByKeyParams struct {
	UserID         uint64
	Mode           string
	IdempotencyKey string
}

func (q *Queries) GetLeaderboardSubmissionByKey(ctx context.Context, arg GetLeaderboardSubmissionByKeyParams) (PlayerLeaderboardSubmission, error) {
	row := q.db.QueryRowContext(ctx, getLeaderboardSubmissionByKey, arg.UserID, arg.Mode, arg.IdempotencyKey)
	var i PlayerLeaderboardSubmission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Mode,
		&i.IdempotencyKey,
		&i.Score,
		&i.Questions,
		&i.ElapsedMs,
		&i.RoomID,
		&i.Outcome,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const listEndlessLeaderboard = `-- name: ListEndlessLeaderboard :many
SELECT submission.user_id,
       u.nickname,
       u.avatar,
       u.nickname_moderation_status,
       u.avatar_moderation_status,
       MAX(submission.score) AS score,
       MAX(submission.created_at) AS last_created_at
FROM player_leaderboard_submissions AS submission
INNER JOIN users AS u ON u.id = submission.user_id
WHERE submission.mode = 'endless' AND u.status = 1
GROUP BY submission.user_id, u.nickname, u.avatar,
         u.nickname_moderation_status, u.avatar_moderation_status
ORDER BY score DESC, submission.user_id ASC
`

type ListEndlessLeaderboardRow struct {
	UserID                   uint64
	Nickname                 string
	Avatar                   string
	NicknameModerationStatus string
	AvatarModerationStatus   string
	Score                    interface{}
	LastCreatedAt            interface{}
}

func (q *Queries) ListEndlessLeaderboard(ctx context.Context) ([]ListEndlessLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, listEndlessLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEndlessLeaderboardRow{}
	for rows.Next() {
		var i ListEndlessLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Nickname,
			&i.Avatar,
			&i.NicknameModerationStatus,
			&i.AvatarModerationStatus,
			&i.Score,
			&i.LastCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendLeaderboard = `-- name: ListFriendLeaderboard :many
SELECT submission.user_id,
       u.nickname,
       u.avatar,
       u.nickname_moderation_status,
       u.avatar_moderation_status,
       MAX(submission.score) AS score,
       MAX(submission.created_at) AS last_created_at
FROM player_leaderboard_submissions AS submission
INNER JOIN users AS u ON u.id = submission.user_id
WHERE submission.mode = 'friend' AND u.status = 1
GROUP BY submission.user_id, u.nickname, u.avatar,
         u.nickname_moderation_status, u.avatar_moderation_status
ORDER BY score DESC, submission.user_id ASC
`

type ListFriendLeaderboardRow struct {
	UserID                   uint64
	Nickname                 string
	Avatar                   string
	NicknameModerationStatus string
	AvatarModerationStatus   string
	Score                    interface{}
	LastCreatedAt            interface{}
}

func (q *Queries) ListFriendLeaderboard(ctx context.Context) ([]ListFriendLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, listFriendLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFriendLeaderboardRow{}
	for rows.Next() {
		var i ListFriendLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Nickname,
			&i.Avatar,
			&i.NicknameModerationStatus,
			&i.AvatarModerationStatus,
			&i.Score,
			&i.LastCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendUserIDs = `-- name: ListFriendUserIDs :many
SELECT DISTINCT candidate.user_id
FROM player_leaderboard_submissions AS candidate
INNER JOIN player_leaderboard_submissions AS mine
    ON mine.mode = 'friend'
   AND mine.user_id = ?
   AND mine.room_id <> ''
   AND mine.room_id = candidate.room_id
WHERE candidate.mode = 'friend'
UNION
SELECT ? AS user_id
`

type ListFriendUserIDsParams struct {
	UserID   uint64
	UserID_2 uint64
}

func (q *Queries) ListFriendUserIDs(ctx context.Context, arg ListFriendUserIDsParams) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, listFriendUserIDs, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var user_id uint64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
