// Code generated by sqlc. DO NOT EDIT.
//
// This file mirrors the queries declared in
// database/queries/leaderboard_submissions.sql.

package db

import (
	"context"
	"time"
)

type PlayerLeaderboardSubmission struct {
	ID             uint64
	UserID         uint64
	Mode           string
	IdempotencyKey string
	Score          uint32
	Questions      uint32
	ElapsedMs      uint32
	RoomID         string
	Outcome        string
	MetadataJSON   string
	CreatedAt      time.Time
}

type GetLeaderboardSubmissionByKeyParams struct {
	UserID         uint64
	Mode           string
	IdempotencyKey string
}

type CreateLeaderboardSubmissionParams struct {
	UserID         uint64
	Mode           string
	IdempotencyKey string
	Score          uint32
	Questions      uint32
	ElapsedMs      uint32
	RoomID         string
	Outcome        string
	MetadataJSON   string
	CreatedAt      time.Time
}

type LeaderboardScoreRow struct {
	UserID        uint64
	Nickname      string
	Avatar        string
	Score         int64
	LastCreatedAt time.Time
}

const getLeaderboardSubmissionByKey = `-- name: GetLeaderboardSubmissionByKey :one
SELECT id, user_id, mode, idempotency_key, score, questions, elapsed_ms, room_id, outcome, metadata_json, created_at
FROM player_leaderboard_submissions
WHERE user_id = ? AND mode = ? AND idempotency_key = ?
LIMIT 1
`

func (q *Queries) GetLeaderboardSubmissionByKey(ctx context.Context, arg GetLeaderboardSubmissionByKeyParams) (PlayerLeaderboardSubmission, error) {
	row := q.db.QueryRowContext(ctx, getLeaderboardSubmissionByKey, arg.UserID, arg.Mode, arg.IdempotencyKey)
	var item PlayerLeaderboardSubmission
	err := row.Scan(
		&item.ID,
		&item.UserID,
		&item.Mode,
		&item.IdempotencyKey,
		&item.Score,
		&item.Questions,
		&item.ElapsedMs,
		&item.RoomID,
		&item.Outcome,
		&item.MetadataJSON,
		&item.CreatedAt,
	)
	return item, err
}

const createLeaderboardSubmission = `-- name: CreateLeaderboardSubmission :exec
INSERT INTO player_leaderboard_submissions (
    user_id,
    mode,
    idempotency_key,
    score,
    questions,
    elapsed_ms,
    room_id,
    outcome,
    metadata_json,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

func (q *Queries) CreateLeaderboardSubmission(ctx context.Context, arg CreateLeaderboardSubmissionParams) error {
	_, err := q.db.ExecContext(ctx, createLeaderboardSubmission,
		arg.UserID,
		arg.Mode,
		arg.IdempotencyKey,
		arg.Score,
		arg.Questions,
		arg.ElapsedMs,
		arg.RoomID,
		arg.Outcome,
		arg.MetadataJSON,
		arg.CreatedAt,
	)
	return err
}

const listEndlessLeaderboard = `-- name: ListEndlessLeaderboard :many
SELECT submission.user_id,
       u.nickname,
       u.avatar,
       MAX(submission.score) AS score,
       MAX(submission.created_at) AS last_created_at
FROM player_leaderboard_submissions AS submission
INNER JOIN users AS u ON u.id = submission.user_id
WHERE submission.mode = 'endless' AND u.status = 1
GROUP BY submission.user_id, u.nickname, u.avatar
ORDER BY score DESC, submission.user_id ASC
`

func (q *Queries) ListEndlessLeaderboard(ctx context.Context) ([]LeaderboardScoreRow, error) {
	rows, err := q.db.QueryContext(ctx, listEndlessLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]LeaderboardScoreRow, 0)
	for rows.Next() {
		var item LeaderboardScoreRow
		if err := rows.Scan(&item.UserID, &item.Nickname, &item.Avatar, &item.Score, &item.LastCreatedAt); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendLeaderboard = `-- name: ListFriendLeaderboard :many
SELECT submission.user_id,
       u.nickname,
       u.avatar,
       MAX(submission.score) AS score,
       MAX(submission.created_at) AS last_created_at
FROM player_leaderboard_submissions AS submission
INNER JOIN users AS u ON u.id = submission.user_id
WHERE submission.mode = 'friend' AND u.status = 1
GROUP BY submission.user_id, u.nickname, u.avatar
ORDER BY score DESC, submission.user_id ASC
`

func (q *Queries) ListFriendLeaderboard(ctx context.Context) ([]LeaderboardScoreRow, error) {
	rows, err := q.db.QueryContext(ctx, listFriendLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]LeaderboardScoreRow, 0)
	for rows.Next() {
		var item LeaderboardScoreRow
		if err := rows.Scan(&item.UserID, &item.Nickname, &item.Avatar, &item.Score, &item.LastCreatedAt); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendUserIDs = `-- name: ListFriendUserIDs :many
SELECT DISTINCT candidate.user_id
FROM player_leaderboard_submissions AS candidate
INNER JOIN player_leaderboard_submissions AS mine
    ON mine.mode = 'friend'
   AND mine.user_id = ?
   AND mine.room_id <> ''
   AND mine.room_id = candidate.room_id
WHERE candidate.mode = 'friend'
UNION
SELECT ? AS user_id
`

func (q *Queries) ListFriendUserIDs(ctx context.Context, userID uint64) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, listFriendUserIDs, userID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]uint64, 0)
	for rows.Next() {
		var item uint64
		if err := rows.Scan(&item); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
