// Code generated by sqlc. DO NOT EDIT.
//
// This file mirrors the queries declared in
// database/queries/leaderboards.sql.

package db

import "context"

import "time"

type CampaignLeaderboardRow struct {
	UserID        uint64
	Nickname      string
	Avatar        string
	Score         int64
	LastCreatedAt time.Time
}

type DailyLeaderboardRow struct {
	UserID    uint64
	Nickname  string
	Avatar    string
	DateKey   string
	Score     uint32
	CreatedAt time.Time
}

const listCampaignLeaderboard = `-- name: ListCampaignLeaderboard :many
SELECT level_scores.user_id,
       u.nickname,
       u.avatar,
       SUM(level_scores.best_score) AS score,
       MAX(level_scores.last_created_at) AS last_created_at
FROM (
    SELECT user_id, level_id, MAX(best_score) AS best_score, MAX(created_at) AS last_created_at
    FROM player_level_completions
    GROUP BY user_id, level_id
) AS level_scores
INNER JOIN users AS u ON u.id = level_scores.user_id
WHERE u.status = 1
GROUP BY level_scores.user_id, u.nickname, u.avatar
ORDER BY score DESC, level_scores.user_id ASC
`

func (q *Queries) ListCampaignLeaderboard(ctx context.Context) ([]CampaignLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := make([]CampaignLeaderboardRow, 0)
	for rows.Next() {
		var item CampaignLeaderboardRow
		if err := rows.Scan(&item.UserID, &item.Nickname, &item.Avatar, &item.Score, &item.LastCreatedAt); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyLeaderboard = `-- name: ListDailyLeaderboard :many
SELECT completion.user_id,
       u.nickname,
       u.avatar,
       completion.date_key,
       completion.best_score AS score,
       completion.created_at
FROM player_daily_completions AS completion
INNER JOIN users AS u ON u.id = completion.user_id
WHERE u.status = 1 AND completion.date_key = ?
ORDER BY completion.best_score DESC, completion.user_id ASC
`

type ListDailyLeaderboardParams struct {
	DateKey string
}

func (q *Queries) ListDailyLeaderboard(ctx context.Context, arg ListDailyLeaderboardParams) ([]DailyLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailyLeaderboard, arg.DateKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := make([]DailyLeaderboardRow, 0)
	for rows.Next() {
		var item DailyLeaderboardRow
		if err := rows.Scan(&item.UserID, &item.Nickname, &item.Avatar, &item.DateKey, &item.Score, &item.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
