// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboards.sql

package db

import (
	"context"
	"time"
)

const listCampaignLeaderboard = `-- name: ListCampaignLeaderboard :many
SELECT level_scores.user_id,
       u.nickname,
       u.avatar,
       u.nickname_moderation_status,
       u.avatar_moderation_status,
       SUM(level_scores.best_score) AS score,
       MAX(level_scores.last_created_at) AS last_created_at
FROM (
    SELECT user_id, level_id, MAX(best_score) AS best_score, MAX(created_at) AS last_created_at
    FROM player_level_completions
    GROUP BY user_id, level_id
) AS level_scores
INNER JOIN users AS u ON u.id = level_scores.user_id
WHERE u.status = 1
GROUP BY level_scores.user_id, u.nickname, u.avatar,
         u.nickname_moderation_status, u.avatar_moderation_status
ORDER BY score DESC, level_scores.user_id ASC
`

type ListCampaignLeaderboardRow struct {
	UserID                   uint64
	Nickname                 string
	Avatar                   string
	NicknameModerationStatus string
	AvatarModerationStatus   string
	Score                    interface{}
	LastCreatedAt            interface{}
}

func (q *Queries) ListCampaignLeaderboard(ctx context.Context) ([]ListCampaignLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCampaignLeaderboardRow{}
	for rows.Next() {
		var i ListCampaignLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Nickname,
			&i.Avatar,
			&i.NicknameModerationStatus,
			&i.AvatarModerationStatus,
			&i.Score,
			&i.LastCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyLeaderboard = `-- name: ListDailyLeaderboard :many
SELECT completion.user_id,
       u.nickname,
       u.avatar,
       u.nickname_moderation_status,
       u.avatar_moderation_status,
       completion.date_key,
       completion.best_score AS score,
       completion.created_at
FROM player_daily_completions AS completion
INNER JOIN users AS u ON u.id = completion.user_id
WHERE u.status = 1 AND completion.date_key = ?
ORDER BY completion.best_score DESC, completion.user_id ASC
`

type ListDailyLeaderboardRow struct {
	UserID                   uint64
	Nickname                 string
	Avatar                   string
	NicknameModerationStatus string
	AvatarModerationStatus   string
	DateKey                  string
	Score                    uint32
	CreatedAt                time.Time
}

func (q *Queries) ListDailyLeaderboard(ctx context.Context, dateKey string) ([]ListDailyLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailyLeaderboard, dateKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailyLeaderboardRow{}
	for rows.Next() {
		var i ListDailyLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Nickname,
			&i.Avatar,
			&i.NicknameModerationStatus,
			&i.AvatarModerationStatus,
			&i.DateKey,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
