// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type User struct {
	ID           uint64
	Username     string
	PasswordHash string
	Nickname     string
	Avatar       string
	Status       uint8
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserIdentity struct {
	ID              uint64
	UserID          uint64
	Provider        string
	ProviderSubject string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type PlayerProfile struct {
	UserID       uint64
	ProgressJSON string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type PlayerLevelCompletion struct {
	ID             uint64
	UserID         uint64
	LevelID        uint32
	IdempotencyKey string
	Score          uint16
	Stars          uint8
	RewardCoins    uint32
	BestScore      uint16
	UnlockedLevel  uint32
	CreatedAt      time.Time
}

type PlayerDailyCompletion struct {
	ID             uint64
	UserID         uint64
	DateKey        string
	IdempotencyKey string
	Score          uint32
	BestScore      uint32
	Streak         uint32
	RewardCoins    uint32
	CreatedAt      time.Time
}
