// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const listUsersForModeration = `-- name: ListUsersForModeration :many
SELECT id, username, password_hash, nickname, avatar, status,
       nickname_moderation_status, avatar_moderation_status,
       moderation_updated_at, created_at, updated_at
FROM users
WHERE id > ?
ORDER BY id ASC
LIMIT ?
`

type ListUsersForModerationParams struct {
	ID    uint64
	Limit int32
}

type ListUsersForModerationRow struct {
	ID                       uint64
	Username                 string
	PasswordHash             string
	Nickname                 string
	Avatar                   string
	Status                   uint8
	NicknameModerationStatus string
	AvatarModerationStatus   string
	ModerationUpdatedAt      sql.NullTime
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

func (q *Queries) ListUsersForModeration(ctx context.Context, arg ListUsersForModerationParams) ([]ListUsersForModerationRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersForModeration, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersForModerationRow{}
	for rows.Next() {
		var i ListUsersForModerationRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Nickname,
			&i.Avatar,
			&i.Status,
			&i.NicknameModerationStatus,
			&i.AvatarModerationStatus,
			&i.ModerationUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordModerationEvent = `-- name: RecordModerationEvent :exec
INSERT INTO user_moderation_events (
    user_id,
    resource_type,
    resource_id,
    source,
    moderation_status,
    reason_code,
    provider_request_id,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type RecordModerationEventParams struct {
	UserID            uint64
	ResourceType      string
	ResourceID        string
	Source            string
	ModerationStatus  string
	ReasonCode        string
	ProviderRequestID string
	CreatedAt         time.Time
}

func (q *Queries) RecordModerationEvent(ctx context.Context, arg RecordModerationEventParams) error {
	_, err := q.db.ExecContext(ctx, recordModerationEvent,
		arg.UserID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Source,
		arg.ModerationStatus,
		arg.ReasonCode,
		arg.ProviderRequestID,
		arg.CreatedAt,
	)
	return err
}

const updateUserModeration = `-- name: UpdateUserModeration :exec
UPDATE users
SET nickname = ?,
    avatar = ?,
    nickname_moderation_status = ?,
    avatar_moderation_status = ?,
    moderation_updated_at = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateUserModerationParams struct {
	Nickname                 string
	Avatar                   string
	NicknameModerationStatus string
	AvatarModerationStatus   string
	ModerationUpdatedAt      sql.NullTime
	UpdatedAt                time.Time
	ID                       uint64
}

func (q *Queries) UpdateUserModeration(ctx context.Context, arg UpdateUserModerationParams) error {
	_, err := q.db.ExecContext(ctx, updateUserModeration,
		arg.Nickname,
		arg.Avatar,
		arg.NicknameModerationStatus,
		arg.AvatarModerationStatus,
		arg.ModerationUpdatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
