// Code generated by sqlc. DO NOT EDIT.
//
// This file mirrors the queries declared in
// database/queries/player_level_completions.sql.

package db

import (
	"context"
	"time"
)

const ensurePlayerProfile = `-- name: EnsurePlayerProfile :exec
INSERT INTO player_profiles (
    user_id,
    progress_json,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE user_id = VALUES(user_id)
`

type EnsurePlayerProfileParams struct {
	UserID       uint64
	ProgressJSON string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) EnsurePlayerProfile(ctx context.Context, arg EnsurePlayerProfileParams) error {
	_, err := q.db.ExecContext(ctx, ensurePlayerProfile,
		arg.UserID,
		arg.ProgressJSON,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getPlayerLevelCompletionByKey = `-- name: GetPlayerLevelCompletionByKey :one
SELECT id, user_id, level_id, idempotency_key, score, stars, reward_coins, best_score, unlocked_level, created_at
FROM player_level_completions
WHERE user_id = ? AND idempotency_key = ?
LIMIT 1
`

type GetPlayerLevelCompletionByKeyParams struct {
	UserID         uint64
	IdempotencyKey string
}

func (q *Queries) GetPlayerLevelCompletionByKey(ctx context.Context, arg GetPlayerLevelCompletionByKeyParams) (PlayerLevelCompletion, error) {
	row := q.db.QueryRowContext(ctx, getPlayerLevelCompletionByKey, arg.UserID, arg.IdempotencyKey)
	var i PlayerLevelCompletion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LevelID,
		&i.IdempotencyKey,
		&i.Score,
		&i.Stars,
		&i.RewardCoins,
		&i.BestScore,
		&i.UnlockedLevel,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerProfileForUpdate = `-- name: GetPlayerProfileForUpdate :one
SELECT user_id, progress_json, created_at, updated_at
FROM player_profiles
WHERE user_id = ?
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetPlayerProfileForUpdate(ctx context.Context, userID uint64) (PlayerProfile, error) {
	row := q.db.QueryRowContext(ctx, getPlayerProfileForUpdate, userID)
	var i PlayerProfile
	err := row.Scan(
		&i.UserID,
		&i.ProgressJSON,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlayerLevelCompletion = `-- name: CreatePlayerLevelCompletion :exec
INSERT INTO player_level_completions (
    user_id,
    level_id,
    idempotency_key,
    score,
    stars,
    reward_coins,
    best_score,
    unlocked_level,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePlayerLevelCompletionParams struct {
	UserID         uint64
	LevelID        uint32
	IdempotencyKey string
	Score          uint16
	Stars          uint8
	RewardCoins    uint32
	BestScore      uint16
	UnlockedLevel  uint32
	CreatedAt      time.Time
}

func (q *Queries) CreatePlayerLevelCompletion(ctx context.Context, arg CreatePlayerLevelCompletionParams) error {
	_, err := q.db.ExecContext(ctx, createPlayerLevelCompletion,
		arg.UserID,
		arg.LevelID,
		arg.IdempotencyKey,
		arg.Score,
		arg.Stars,
		arg.RewardCoins,
		arg.BestScore,
		arg.UnlockedLevel,
		arg.CreatedAt,
	)
	return err
}

const updatePlayerProfileProgress = `-- name: UpdatePlayerProfileProgress :exec
UPDATE player_profiles
SET progress_json = ?, updated_at = ?
WHERE user_id = ?
`

type UpdatePlayerProfileProgressParams struct {
	ProgressJSON string
	UpdatedAt    time.Time
	UserID       uint64
}

func (q *Queries) UpdatePlayerProfileProgress(ctx context.Context, arg UpdatePlayerProfileProgressParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerProfileProgress,
		arg.ProgressJSON,
		arg.UpdatedAt,
		arg.UserID,
	)
	return err
}
