// Code generated by sqlc. DO NOT EDIT.
//
// This file mirrors the queries declared in
// database/queries/player_daily_completions.sql.

package db

import (
	"context"
	"time"
)

const getPlayerDailyCompletionByDate = `-- name: GetPlayerDailyCompletionByDate :one
SELECT id, user_id, date_key, idempotency_key, score, best_score, streak, reward_coins, created_at
FROM player_daily_completions
WHERE user_id = ? AND date_key = ?
LIMIT 1
`

type GetPlayerDailyCompletionByDateParams struct {
	UserID  uint64
	DateKey string
}

func (q *Queries) GetPlayerDailyCompletionByDate(ctx context.Context, arg GetPlayerDailyCompletionByDateParams) (PlayerDailyCompletion, error) {
	row := q.db.QueryRowContext(ctx, getPlayerDailyCompletionByDate, arg.UserID, arg.DateKey)
	var i PlayerDailyCompletion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DateKey,
		&i.IdempotencyKey,
		&i.Score,
		&i.BestScore,
		&i.Streak,
		&i.RewardCoins,
		&i.CreatedAt,
	)
	return i, err
}

const createPlayerDailyCompletion = `-- name: CreatePlayerDailyCompletion :exec
INSERT INTO player_daily_completions (
    user_id,
    date_key,
    idempotency_key,
    score,
    best_score,
    streak,
    reward_coins,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePlayerDailyCompletionParams struct {
	UserID         uint64
	DateKey        string
	IdempotencyKey string
	Score          uint32
	BestScore      uint32
	Streak         uint32
	RewardCoins    uint32
	CreatedAt      time.Time
}

func (q *Queries) CreatePlayerDailyCompletion(ctx context.Context, arg CreatePlayerDailyCompletionParams) error {
	_, err := q.db.ExecContext(ctx, createPlayerDailyCompletion,
		arg.UserID,
		arg.DateKey,
		arg.IdempotencyKey,
		arg.Score,
		arg.BestScore,
		arg.Streak,
		arg.RewardCoins,
		arg.CreatedAt,
	)
	return err
}
