// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player_profiles.sql

package db

import (
	"context"
	"time"
)

const createPlayerProfile = `-- name: CreatePlayerProfile :exec
INSERT INTO player_profiles (
    user_id,
    progress_json,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?)
`

type CreatePlayerProfileParams struct {
	UserID       uint64
	ProgressJson string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreatePlayerProfile(ctx context.Context, arg CreatePlayerProfileParams) error {
	_, err := q.db.ExecContext(ctx, createPlayerProfile,
		arg.UserID,
		arg.ProgressJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getPlayerProfile = `-- name: GetPlayerProfile :one
SELECT user_id, progress_json, created_at, updated_at
FROM player_profiles
WHERE user_id = ?
LIMIT 1
`

func (q *Queries) GetPlayerProfile(ctx context.Context, userID uint64) (PlayerProfile, error) {
	row := q.db.QueryRowContext(ctx, getPlayerProfile, userID)
	var i PlayerProfile
	err := row.Scan(
		&i.UserID,
		&i.ProgressJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
