// Code generated by sqlc. DO NOT EDIT.
//
// This file mirrors the queries declared in database/queries/player_profiles.sql. It is
// kept in the generated package so the application continues to use the same
// database access boundary when sqlc is unavailable in a local environment.

package db

import (
	"context"
	"time"
)

const getPlayerProfile = `-- name: GetPlayerProfile :one
SELECT user_id, progress_json, created_at, updated_at
FROM player_profiles
WHERE user_id = ?
LIMIT 1
`

func (q *Queries) GetPlayerProfile(ctx context.Context, userID uint64) (PlayerProfile, error) {
	row := q.db.QueryRowContext(ctx, getPlayerProfile, userID)
	var i PlayerProfile
	err := row.Scan(
		&i.UserID,
		&i.ProgressJSON,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlayerProfile = `-- name: CreatePlayerProfile :exec
INSERT INTO player_profiles (
    user_id,
    progress_json,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?)
`

type CreatePlayerProfileParams struct {
	UserID       uint64
	ProgressJSON string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreatePlayerProfile(ctx context.Context, arg CreatePlayerProfileParams) error {
	_, err := q.db.ExecContext(ctx, createPlayerProfile,
		arg.UserID,
		arg.ProgressJSON,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
