// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetLeaderboardSubmissionByKey(ctx context.Context, arg GetLeaderboardSubmissionByKeyParams) (PlayerLeaderboardSubmission, error)
	CreateLeaderboardSubmission(ctx context.Context, arg CreateLeaderboardSubmissionParams) error
	ListEndlessLeaderboard(ctx context.Context) ([]LeaderboardScoreRow, error)
	ListFriendLeaderboard(ctx context.Context) ([]LeaderboardScoreRow, error)
	ListFriendUserIDs(ctx context.Context, userID uint64) ([]uint64, error)
	ListCampaignLeaderboard(ctx context.Context) ([]CampaignLeaderboardRow, error)
	ListDailyLeaderboard(ctx context.Context, arg ListDailyLeaderboardParams) ([]DailyLeaderboardRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) error
	CreatePlayerProfile(ctx context.Context, arg CreatePlayerProfileParams) error
	CreatePlayerLevelCompletion(ctx context.Context, arg CreatePlayerLevelCompletionParams) error
	CreatePlayerDailyCompletion(ctx context.Context, arg CreatePlayerDailyCompletionParams) error
	DisableUser(ctx context.Context, arg DisableUserParams) error
	EnsurePlayerProfile(ctx context.Context, arg EnsurePlayerProfileParams) error
	GetPlayerLevelCompletionByKey(ctx context.Context, arg GetPlayerLevelCompletionByKeyParams) (PlayerLevelCompletion, error)
	GetPlayerDailyCompletionByDate(ctx context.Context, arg GetPlayerDailyCompletionByDateParams) (PlayerDailyCompletion, error)
	GetPlayerProfileForUpdate(ctx context.Context, userID uint64) (PlayerProfile, error)
	GetPlayerProfile(ctx context.Context, userID uint64) (PlayerProfile, error)
	GetUserByID(ctx context.Context, id uint64) (User, error)
	GetUserByProviderSubject(ctx context.Context, arg GetUserByProviderSubjectParams) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpdatePlayerProfileProgress(ctx context.Context, arg UpdatePlayerProfileProgressParams) error
}

var _ Querier = (*Queries)(nil)
