// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
    username,
    password_hash,
    nickname,
    avatar,
    status,
    nickname_moderation_status,
    avatar_moderation_status,
    moderation_updated_at,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, COALESCE(NULLIF(?, ''), 'approved'), COALESCE(NULLIF(?, ''), 'approved'), ?, ?, ?)
`

type CreateUserParams struct {
	Username                 string
	PasswordHash             string
	Nickname                 string
	Avatar                   string
	Status                   uint8
	NicknameModerationStatus string
	AvatarModerationStatus   string
	ModerationUpdatedAt      *time.Time
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Nickname,
		arg.Avatar,
		arg.Status,
		arg.NicknameModerationStatus,
		arg.AvatarModerationStatus,
		arg.ModerationUpdatedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createUserIdentity = `-- name: CreateUserIdentity :exec
INSERT INTO user_identities (
    user_id,
    provider,
    provider_subject,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?)
`

type CreateUserIdentityParams struct {
	UserID          uint64
	Provider        string
	ProviderSubject string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createUserIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const disableUser = `-- name: DisableUser :exec
UPDATE users
SET status = 0, updated_at = ?
WHERE id = ?
`

type DisableUserParams struct {
	UpdatedAt time.Time
	ID        uint64
}

func (q *Queries) DisableUser(ctx context.Context, arg DisableUserParams) error {
	_, err := q.db.ExecContext(ctx, disableUser, arg.UpdatedAt, arg.ID)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, nickname, avatar, status,
       nickname_moderation_status, avatar_moderation_status,
       moderation_updated_at, created_at, updated_at
FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uint64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.Status,
		&i.NicknameModerationStatus,
		&i.AvatarModerationStatus,
		&i.ModerationUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProviderSubject = `-- name: GetUserByProviderSubject :one
SELECT u.id, u.username, u.password_hash, u.nickname, u.avatar, u.status,
       u.nickname_moderation_status, u.avatar_moderation_status,
       u.moderation_updated_at, u.created_at, u.updated_at
FROM users AS u
INNER JOIN user_identities AS identity_record ON identity_record.user_id = u.id
WHERE identity_record.provider = ? AND identity_record.provider_subject = ?
LIMIT 1
`

type GetUserByProviderSubjectParams struct {
	Provider        string
	ProviderSubject string
}

func (q *Queries) GetUserByProviderSubject(ctx context.Context, arg GetUserByProviderSubjectParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByProviderSubject, arg.Provider, arg.ProviderSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.Status,
		&i.NicknameModerationStatus,
		&i.AvatarModerationStatus,
		&i.ModerationUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, nickname, avatar, status,
       nickname_moderation_status, avatar_moderation_status,
       moderation_updated_at, created_at, updated_at
FROM users
WHERE username = ?
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.Status,
		&i.NicknameModerationStatus,
		&i.AvatarModerationStatus,
		&i.ModerationUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET nickname = ?,
    avatar = ?,
    nickname_moderation_status = COALESCE(NULLIF(?, ''), nickname_moderation_status),
    avatar_moderation_status = COALESCE(NULLIF(?, ''), avatar_moderation_status),
    moderation_updated_at = COALESCE(?, moderation_updated_at),
    updated_at = ?
WHERE id = ?
`

type UpdateUserProfileParams struct {
	Nickname                 string
	Avatar                   string
	NicknameModerationStatus string
	AvatarModerationStatus   string
	ModerationUpdatedAt      *time.Time
	UpdatedAt                time.Time
	ID                       uint64
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.Nickname,
		arg.Avatar,
		arg.NicknameModerationStatus,
		arg.AvatarModerationStatus,
		arg.ModerationUpdatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
